### ISSUE TITLE
Kalman smoother

### ISSUE THREAD

**Issue by mschauer** [JuliaStats/TimeModels.jl#35]
The smoother is missing a line
``  P_pred = model.F * P[:, :, i] * model.F' + model.V``
in the loop.

**Comment by mschauer** [comment]
Also I think lines https://github.com/JuliaStats/TimeModels.jl/blob/master/src/Kalman.jl#L172 to L175 are wrong and have to be removed.

**Comment by milktrader** [comment]
Could you do a PR? And how did you discover this? Maybe we can put in a test?

I'll merge it if there is no objection after a week or so, unless someone else wants to merge it sooner

**Comment by milktrader** [comment]
@ElOceanografo wrote the Kalman code.

**Comment by mschauer** [comment]
I found it because I implemented it myself and wanted to check my implementation. 

By now there are too many implementations,
https://github.com/ElOceanografo/StateSpace.jl
https://github.com/JuliaStats/TimeModels.jl
https://github.com/wkearn/Kalman.jl
https://github.com/setzler/JuliaEconomics/blob/master/Tutorials/tutorial_6_noglobals.jl
and, well, https://gist.github.com/mschauer/3ffebdb8581f56341a9d

maybe we can do some serious coordination ;-)
cc @wkean, @setzler

**Comment by milktrader** [comment]
Agreed! I think JuliaStats would be a natural place for this. Whether it stays in TimeModels or gets its own package is a good discussion.

**Comment by mschauer** [comment]
Let's keep this issue for the mistake and move to https://github.com/JuliaStats/Roadmap.jl/issues/16

**Comment by milktrader** [comment]
Thanks for doing this!

**Comment by GordStephen** [comment]
Fixed in https://github.com/JuliaStats/TimeModels.jl/pull/38
