### ISSUE TITLE
Is TimeModels.jl still being developed/maintained?

### ISSUE THREAD

**Issue by GordStephen** [JuliaStats/TimeModels.jl#36]
I've been running into some issues with this module, but it's been quiet here for a while and I know there was some discussion in https://github.com/JuliaStats/Roadmap.jl/issues/16 about consolidating efforts in this area, so before I started filing issues/PRs I wanted to make sure this was still under active development.

I'd love to see the functionality here maintained and expanded, and would be happy to contribute to doing so - just want to make sure I'm not missing a parallel project or duplicating functionality from elsewhere.

**Comment by milktrader** [comment]
Yeah, it's a little behind for sure. If you want to start actively organizing/updating it, I'll be happy to give you commit access.

**Comment by GordStephen** [comment]
Sure, happy to help. For now I'll probably just start small with bugfixes and getting the tests up and running, and eventually ramp up to broader organizational stuff.

**Comment by milktrader** [comment]
Welcome aboard! You also have access to TimeSeries, but that one is a bit more sensitive to changes than TimeModels and will require consensus before making breaking (or other major) changes.

For now have at it with TimeModels. Things like adding tests will not require consent so much, but it will be nice to have a *paper trail* with issues being filed and closed.

**Comment by GordStephen** [comment]
Great, will do, thanks.
