### ISSUE TITLE
Isolate versions that support only Julia 0.3 and Julia 0.4

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeModels.jl#46]
This would put an end to development for Julia 0.3 and isolate a version as the last minor version that points to it. The REQUIRE would be

```` 
julia 0.3 0.4-
```` 

The next development cycle should then focus only on Julia 0.4 and exclude Julia 0.5, where there is expected to be quite a bit of turmoil. The REQUIRE would be as follows:

````
julia 0.4- 0.5-
````
Once release candidates are completed, the `0.4-` should change to `0.4`.

This code base needs some coherence first I think. @codles and @GordStephen

**Comment by GordStephen** [comment]
https://github.com/JuliaStats/TimeModels.jl/pull/43 still needs some more work and I'm not sure when I'll get to it, so I would say if @codles implements time-varying parameter matrices as generator functions (as discussed in #42), we should go ahead with that as the first 0.4-only release - I'll go back later and rebase/merge my work as necessary after the fact.

**Comment by milktrader** [comment]
Recent   4cbbea4c09125276a917ece2ed1174e01babc41e starts this process, and once we're satisfied with where it is on Julia 0.3 then we can close that door and begin development on support for Julia 0.4 only.
