### ISSUE TITLE
Does new Kalman code require Julia 0.4?

### ISSUE THREAD

**Issue by milktrader** [JuliaStats/TimeModels.jl#47]
I've removed the `@compat` macro from code that only supports Julia 0.3 but it breaks the package.

One solution is to put that code back in and have an expected support for Julia 0.3 and 0.4-, instead of *only* supporting Julia 0.3. @codles thoughts?

This is not a big deal since we can make 0.1.0 *only* support Julia 0.4- to 0.5- and then allow 0.0.3 to support both Julia 0.3 and 0.4- with the Compat package.

**Comment by codles** [comment]
'@compat' was required as `Union()` was changed to 'Union{}' between v0.3 and v0.4.
Everything else should work in both v0.3 and v0.4.

I prefer supporting v0.3 and v0.4 using compat.

**Comment by milktrader** [comment]
Ok, I'll change things to support 0.3 to 0.4- for now. Version 0.0.3 will then support both via the Compat package. We can then isolate support for only 0.4 later on with a tag of 0.1.0
