### ISSUE TITLE
Coverage testing

### ISSUE THREAD

**Issue by GordStephen** [JuliaStats/TimeModels.jl#51]
It would be good have coveralls.io support eventually.

**Comment by milktrader** [comment]
It seems they've changed their API to allowing access. I signed in and it wanted to authorize access to too many organizations. I can look into this later.

**Comment by GordStephen** [comment]
I added coverage support in #52 and it seems to be working - https://coveralls.io/github/JuliaStats/TimeModels.jl - I'll close this when that PR gets merged.

**Comment by GordStephen** [comment]
Added in #52
