### ISSUE TITLE
Is GARCH tested?

### ISSUE THREAD

**Issue by pkofod** [JuliaStats/TimeModels.jl#62]
Updating Optim I came across this https://github.com/JuliaStats/TimeModels.jl/blob/906bf811d62544e43c755d5cf2d9aa2a52115216/src/GARCH.jl#L104 . The 3-touple output has not been in Optim for a long time, so I am wondering if you are testing this properly? I would have to guess that this code would cause an error with any somewhat recent Optim version.

**Comment by GordStephen** [comment]
That's likely - this package has been somewhat dormant for a while. We had some momentum on state-space models last fall but not too much work on the GARCH front.
